version: "3"

services:
  paopaodns:
    image: sliamb/paopaodns:latest
    container_name: PaoPaoDNS
    restart: always
    volumes:
      - /share/Container/paopaodns:/data
    environment:
      - TZ=Asia/Shanghai
      - UPDATE=weekly
      - DNS_SERVERNAME=PaoPaoDNS,blog.03k.org
      - DNSPORT=53
      - SOCKS5=no
      - CNAUTO=yes
      - IPV6=no
      - CNFALL=yes
      - CUSTOM_FORWARD=10.10.10.3:53
      - AUTO_FORWARD=no
      - CN_TRACKER=yes
      - SAFEMODE=no
    ports:
      - "53:53/udp"
      - "53:53/tcp"
      - "5304:5304/ucp"
      - "5304:5304/tcp"
      - "7889:7889/tcp"