name: "Help need"
description: "[请求帮助] 搭建失败？或者没有按照期望的效果？"
title: "[Help] "
labels: "help wanted"
body:
  - type: markdown
    attributes:
      value: "描述越详细越有助于定位和解决问题，请及时提供有效信息的反馈。"

  - type: checkboxes
    id: pre-check
    attributes:
      label: "在提交之前，请确认"
      options:
        - label: "我已经尝试搜索过Issue和看过参数说明，但没有找到相关问题。"
          required: true
        - label: "我正在使用最新的docker镜像版本（可以尝试`docker pull sliamb/paopaodns:latest`后重新创建容器，如果不确定的话可以尝试使用`sliamb/paopaodns:dev`）。"
          required: true

  - type: textarea
    id: log
    attributes:
      label: 脚本自检日志
      description: "在容器内执行`debug.sh`，将输出结果粘贴到https://gist.github.com ，如有敏感信息可以用x代替最后一位"
      render: txt
    validations:
      required: true

  - type: textarea
    id: what-happened
    attributes:
      label: 问题描述和复现步骤
      description: "描述越详细越有助于定位和解决问题。"
      placeholder: "问题描述："
    validations:
      required: true

